export const vibesData = [
  {
    id: 1,
    mood: 'Calm',
    moodColor: '#A9C7FF',
    text: 'Rain on the window. Tea going cold. Not fixing it.',
    timestamp: '2h ago',
    dreamOrb: true,
    author: 'Yuki Tanaka',
    authorUsername: 'yuki_t',
    authorColor: '#A9C7FF',
    isFollowing: true,
  },
  {
    id: 2,
    mood: 'Dreamy',
    moodColor: '#C5A9FF',
    text: 'ok so i was literally floating through purple clouds last night?? like full-on swimming through them. idk what my brain is doing lol',
    timestamp: '5h ago',
    image: 'https://images.unsplash.com/photo-1682335688718-cd3c073bd18b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb2Z0JTIwZHJlYW15JTIwc2t5fGVufDF8fHx8MTc2MjMzMzM2NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    author: 'Mateo Silva',
    authorUsername: 'mateo_s',
    authorColor: '#C5A9FF',
    isFollowing: true,
  },
  {
    id: 3,
    mood: 'Sad',
    moodColor: '#A9B8D9',
    text: 'Not a great day. Not looking for advice, just letting it be here for a second.',
    timestamp: '4h ago',
    dreamOrb: true,
    author: 'Zara Ahmed',
    authorUsername: 'zara_a',
    authorColor: '#A9B8D9',
    isFollowing: true,
  },
  {
    id: 4,
    mood: 'Creative',
    moodColor: '#D4A9FF',
    text: 'THREE ideas hit me in the shower, TWO more on the bus, and now I can\'t type fast enough — brain is FULLY unhinged today and I am HERE for it',
    timestamp: '6h ago',
    author: 'Luca Rossi',
    authorUsername: 'luca_r',
    authorColor: '#D4A9FF',
    isFollowing: true,
  },
  {
    id: 5,
    mood: 'Reflective',
    moodColor: '#E0C9D9',
    text: 'I\'ve been thinking about how we spend so much energy trying to resolve feelings rather than simply allowing them to exist. There\'s something quietly radical about just sitting with discomfort.',
    timestamp: '8h ago',
    author: 'Priya Patel',
    authorUsername: 'priya_p',
    authorColor: '#E0C9D9',
    isFollowing: true,
  },
  {
    id: 6,
    mood: 'Angry',
    moodColor: '#FFA9A9',
    text: 'Frustrated. Tired. Venting into the void. Carry on.',
    timestamp: '10h ago',
    author: 'Kai Schmidt',
    authorUsername: 'kai_s',
    authorColor: '#FFA9A9',
    isFollowing: true,
  },
  {
    id: 7,
    mood: 'Calm',
    moodColor: '#A9C7FF',
    text: 'The morning fog came in low and slow, hugging the rooftops like it had nowhere else to be. Watched it dissolve for almost an hour. Some mornings you just have to let the world be beautiful at you.',
    timestamp: '12h ago',
    image: 'https://images.unsplash.com/photo-1737023590121-0dfc4ee96fb6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMG1pc3QlMjBwYXN0ZWx8ZW58MXx8fHwxNzYyMzMzMzY2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    author: 'Amara Okafor',
    authorUsername: 'amara_o',
    authorColor: '#A9C7FF',
    isFollowing: true,
  },
  {
    id: 8,
    mood: 'Hopeful',
    moodColor: '#FFD4A9',
    text: 'Idk, today just feels different. Like something good is on its way and I\'m not even going to question it.',
    timestamp: '1d ago',
    author: 'Diego Morales',
    authorUsername: 'diego_m',
    authorColor: '#FFD4A9',
    isFollowing: true,
  },
  {
    id: 9,
    mood: 'Energetic',
    moodColor: '#FFB8A9',
    text: 'WOKE UP AND CHOSE CHAOS (the good kind) 🔥 everything is possible today and I will not be taking questions!!',
    timestamp: '1d ago',
    author: 'Nina Kowalski',
    authorUsername: 'nina_k',
    authorColor: '#FFB8A9',
    isFollowing: false,
  },
  {
    id: 10,
    mood: 'Anxious',
    moodColor: '#D9C5B8',
    text: 'Brain won\'t slow down tonight. Just breathing. Noticing the breath. Coming back when I drift. It\'s enough.',
    timestamp: '1d ago',
    author: 'Ravi Kumar',
    authorUsername: 'ravi_k',
    authorColor: '#D9C5B8',
    isFollowing: true,
  },
];
