export const vibesData = [
  {
    id: 1,
    mood: 'Calm',
    moodColor: '#A9C7FF',
    text: 'Rainy day vibes. Just sitting here listening to the drops on the window',
    timestamp: '2h ago',
    dreamOrb: true,
    author: 'Yuki Tanaka',
    authorUsername: 'yuki_t',
    authorColor: '#A9C7FF',
    isFollowing: true,
  },
  {
    id: 2,
    mood: 'Dreamy',
    moodColor: '#C5A9FF',
    text: 'weird dream last night... i was literally floating through purple clouds lol',
    timestamp: '5h ago',
    image: 'https://images.unsplash.com/photo-1682335688718-cd3c073bd18b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb2Z0JTIwZHJlYW15JTIwc2t5fGVufDF8fHx8MTc2MjMzMzM2NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    author: 'Mateo Silva',
    authorUsername: 'mateo_s',
    authorColor: '#C5A9FF',
    isFollowing: true,
  },
  {
    id: 3,
    mood: 'Sad',
    moodColor: '#A9B8D9',
    text: 'Not a great day but that\'s okay. Just gonna let myself feel it',
    timestamp: '4h ago',
    dreamOrb: true,
    author: 'Zara Ahmed',
    authorUsername: 'zara_a',
    authorColor: '#A9B8D9',
    isFollowing: true,
  },
  {
    id: 4,
    mood: 'Creative',
    moodColor: '#D4A9FF',
    text: 'so many ideas today i can\'t even keep up. brain is on fire rn',
    timestamp: '6h ago',
    author: 'Luca Rossi',
    authorUsername: 'luca_r',
    authorColor: '#D4A9FF',
    isFollowing: true,
  },
  {
    id: 5,
    mood: 'Reflective',
    moodColor: '#E0C9D9',
    text: 'Sometimes you just gotta sit with your feelings for a bit',
    timestamp: '8h ago',
    author: 'Priya Patel',
    authorUsername: 'priya_p',
    authorColor: '#E0C9D9',
    isFollowing: true,
  },
  {
    id: 6,
    mood: 'Angry',
    moodColor: '#FFA9A9',
    text: 'Really frustrated rn. Just need to vent and let it out',
    timestamp: '10h ago',
    author: 'Kai Schmidt',
    authorUsername: 'kai_s',
    authorColor: '#FFA9A9',
    isFollowing: true,
  },
  {
    id: 7,
    mood: 'Calm',
    moodColor: '#A9C7FF',
    text: 'Morning fog this morning was beautiful. Watched it clear up from my window',
    timestamp: '12h ago',
    image: 'https://images.unsplash.com/photo-1737023590121-0dfc4ee96fb6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhYnN0cmFjdCUyMG1pc3QlMjBwYXN0ZWx8ZW58MXx8fHwxNzYyMzMzMzY2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral',
    author: 'Amara Okafor',
    authorUsername: 'amara_o',
    authorColor: '#A9C7FF',
    isFollowing: true,
  },
  {
    id: 8,
    mood: 'Hopeful',
    moodColor: '#FFD4A9',
    text: 'Idk why but today just feels different. Like good things are coming',
    timestamp: '1d ago',
    author: 'Diego Morales',
    authorUsername: 'diego_m',
    authorColor: '#FFD4A9',
    isFollowing: true,
  },
  {
    id: 9,
    mood: 'Energetic',
    moodColor: '#FFB8A9',
    text: 'Can\'t stop moving today! Everything feels possible',
    timestamp: '1d ago',
    author: 'Nina Kowalski',
    authorUsername: 'nina_k',
    authorColor: '#FFB8A9',
    isFollowing: false,
  },
  {
    id: 10,
    mood: 'Anxious',
    moodColor: '#D9C5B8',
    text: 'Brain won\'t shut off. Trying to just breathe through it',
    timestamp: '1d ago',
    author: 'Ravi Kumar',
    authorUsername: 'ravi_k',
    authorColor: '#D9C5B8',
    isFollowing: true,
  },
];